name: Deploy Infrastructure

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Terraform Init
        working-directory: ./infrastructure/
        run: terraform init

      - name: Terraform Apply
        working-directory: ./infrastructure/
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Get Bucket Name from Terraform Output
        id: get_bucket
        working-directory: ./infrastructure/
        run: |
          BUCKET_NAME=$(terraform output -raw s3_bucket_name)
          echo "bucket_name=$BUCKET_NAME" >> "$GITHUB_OUTPUT"

      - name: Upload files to S3
        run: |
          echo "Uploading to bucket: ${{ steps.get_bucket.outputs.bucket_name }}"
          aws s3 cp sample_files/ s3://${{ steps.get_bucket.outputs.bucket_name }}/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
