name: Test Lambda Function

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1

jobs:
  test-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Python syntax
        run: |
          python3 -m py_compile app/list_s3_objects_and_notify.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Invoke Lambda and print output
        run: |
          aws lambda invoke \
            --function-name list-s3-and-notify \
            --payload '{"test": "manual-trigger"}' \
            --cli-binary-format raw-in-base64-out \
            response.json
          echo "Lambda output:"
          cat response.json